### ISSUE TITLE
Create a readme

### ISSUE THREAD

**Issue by AkhileshManda** [PrajasW/code6#1]
Create a README.md file describing the teams interest and goals. Try to make ur goals as clear as possible in the form of checkboxes and keep updating them as you reach the goals. Interested person comment on the issue and I'll assign it to them so you guys can start working

**Comment by AkhileshManda** [comment]
@PrajasW I am assigning you this issue, try to get it done by tom.

**Comment by PrajasW** [comment]
Created Basic Layout Will do improvements Soon
